## Numpy:
Task_14_Numpy Theory:

## Describe the features of numpy.

### Numpy is a library of python,can solve complex numerical problems using python numpy
* numpy has many methods which can be used to solve numerious problems ex: statics,probability,algebra
* numpy is 10x faster than the actual python
* numpy can also deal with n dimentional arrays

## Write the applications of numpy.

* data analysics
* mathematics computing
* file handling
* data visualization

## How numpy is different from python sequences.

* numpy data elements can only contain datatypes of same type ,Homogenious
* python sequences  Can store mixed data types,heterogenious
* numpy data elements are easier to access while compared to python sequences
* numpy data elements manipulation is easier than python sequences because of various numpy methods

## Create two 1-D arrays with numbers and strings respectively.

In [10]:
import numpy as np
arr=np.array([1,5,4,6])
print(type(arr),arr.ndim)

<class 'numpy.ndarray'> 1


### Create 2-D and 3-D arrays. And check their shape and dimensions using (shape and ndim methods).

In [27]:
import numpy as np
arr1=np.array([[1,5,4,6],[4,5,5,5]])
print(arr1.shape,arr1.ndim)
arr2=np.array([[[1,5,4,6],
                [4,5,5,5],
                [5,84,15,25]]])
print(arr2.shape,arr2.ndim)

(2, 4) 2
(1, 3, 4) 3


## Explain Data Analysis in your own words using a markdown cell.

### Data Analysis is the process of analyzing the data of different types and summarizing it to get desired outcome like
* searching,finding
* cleaning
* sorting
* analyzing
* solving problems

## Creation of numpy with different methods:

### Create a 1D NumPy array with elements from 1 to 10 using arange().

In [4]:
import numpy as np
ele=np.arange(1,11)
print(ele,ele.ndim)

[ 1  2  3  4  5  6  7  8  9 10] 1


### Create a 2D array of size 3x3 filled with zeros using zeros().

In [13]:
elezero=np.zeros((3,3))
print(elezero,elezero.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)


### Create an array [5, 10, 15, 20, 25]. Find its size, item size, and total bytes used by the array.

In [28]:
anarray=np.array([5, 10, 15, 20, 25])
print(f"array size:{anarray.size} '\n'{anarray.itemsize},'\n',{anarray.tobytes}")

array size:5 '
'8,'
',<built-in method tobytes of numpy.ndarray object at 0x0000028CC371AC10>


### Use linspace() to generate an array of 7 equally spaced numbers between 0 and 14.

In [31]:
arrlinespace=np.linspace(0,14,7)
arrlinespace

array([ 0.        ,  2.33333333,  4.66666667,  7.        ,  9.33333333,
       11.66666667, 14.        ])

### Create a 4x4 identity matrix using eye().

In [34]:
arreye=np.eye(4)
print(arreye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Create a 3x3 diagonal matrix with the diagonal values [1, 2, 3] using diag().

In [38]:
arrdiag=np.diag([1,2,3])
print(arrdiag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


### Create a 2x3 array filled with the value 9 using full().

In [43]:
arrfull=np.full((2,2),9)
print(arrfull)

[[9 9]
 [9 9]]


### Generate a 3x3 array of random numbers between 0 and 1 using random.rand().

In [52]:
arrrand=np.random.rand(3,3)
print(arrrand)

[[0.30214636 0.25371867 0.01137361]
 [0.76817055 0.1560083  0.36439377]
 [0.49525221 0.36098956 0.01041808]]


### Create a 4x4 array of random integers between 10 and 50 using random.randint().

In [55]:
arrrandint=np.random.randint(10,50,(4,4))
print(arrrandint)

[[11 44 29 21]
 [25 43 45 47]
 [13 16 10 14]
 [26 38 16 28]]


### Generate a 1D array of 5 random numbers from a normal distribution using random.randn().

In [59]:
arrrandn=np.random.randn(5)
arrrandn

array([ 0.19113923,  0.34891914, -1.1340682 , -0.54501376, -0.14919441])

### Generate a 2D array of shape (2, 4) with random values uniformly distributed between -5 and 5 using random.uniform().

In [65]:
arruni=np.random.uniform(-5,5,(2,4))
arruni

array([[ 4.98654358,  3.59523662, -4.29523889,  0.29787801],
       [ 3.42469036, -4.78509388, -1.6314122 , -1.40361883]])

### Create a 1D array [10, 20, 30, 40, 50]. Access the third element and update it to 35.

In [68]:
arroned=np.array([10, 20, 30, 40, 50])
arroned[2]=35
arroned

array([10, 20, 35, 40, 50])

### Create a 2D array of shape (3, 4) with values from 1 to 12.

In [76]:
arrtwod=np.arange(1,13)
arrtwod.resize((3,4))
arrtwod

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

###  Slice and extract the second row.

In [83]:
arrtwod[1:2]

array([[5, 6, 7, 8]])

### From the same array, extract all elements in the last column.

In [92]:
print(arrtwod[2:].view())

[[ 9 10 11 12]]


### Create a 3x3 array of ones using ones() and change its dtype to int.

In [105]:
arrones=np.ones((3,3),dtype=int)
arrones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Create an array [1, 2, 3, 4, 5] and multiply each element by 2.

In [108]:
arrmul=np.array([1, 2, 3, 4, 5] )
arrmul*2

array([ 2,  4,  6,  8, 10])